# Neural Networks 

####  What is a neural network?
Neural network is a machine learning method that is loosely inspired by neurons in the brain. What they do is multiply weights and inputs. If we're given a training set of inputs and outputs it will learn the mapping by continously updating weights to get nearer to the output. 
### Neural Networks look like this
![](http://neuralnetworksanddeeplearning.com/images/tikz35.png)

### Let's start with a simple example

In [3]:
import numpy as np
def Neural_Network(input, weight):
    return input * weight
weight = np.random.randn(1)

In [4]:
Neural_Network(0.2354, weight)

array([-0.04018835])

This is what neural networks do! They multiply weights and inputs to get a prediction. 

### Working  with multiple inputs and weights
For this example we'll work with 4 inputs and weights

In [5]:
weight = np.random.randn(4)
np.random.seed(1)
input = np.array([2.3, 4.6, 7.8, 0.9])
print(Neural_Network(weight, input))

[-5.76592401  3.87182717  2.21030535  0.10135316]


Oops! We get more than one result. So, we need to sum these all results to get a prediction. So, We need to define a weighted sum funtion. We can do this by numpy 'dot' function

In [6]:
np.dot(input, weight)#We're gonna be using this instead of Neural_Network function that we defined above

0.41756167300040448

#### This is what the neural network that we coded looks like
![This is how our neural network looks like](http://www.theprojectspot.com/images/post-assets/an.jpg)

## Let's do this with an example
#### Will it rain or not

#### What is this Activation Function(f) in the above picture
What if we want to predict whether it'll rain or not. We can have some inputs(features)) 'X', Weights ' W' and Output 'Y'
The formula would be " X * W = Y' where 'Y' is the probability of Raining. From the program above that's not the case as it is not the prbability. That's were activation functions come in play!

There are alot of activation functions. Here we're gonna be using Sigmoid function that will convert the result into a probability between 0 and 1
![Activatio Function](https://qph.ec.quoracdn.net/main-qimg-05edc1873d0103e36064862a45566dba)

In [25]:
#We need to define the sigmoid function
def sigmoid(x):
    return 1/(1 + np.exp(-x))
#Now take the sigmoid of the dot product
print(sigmoid(np.dot(input, weight)))

0.602899632657


So, our model predicts that there is 99% chance of raining. But this may be wrong as multiplying inputs and random weights will give us random results. We need the correct weghts for the model to predict accurately 

## Let's do this with an example 

In [24]:
import numpy as np 
inputs = np.array([[1, 0, 1], [0, 0, 1], [1, 1, 1], [0,0,0]]) #inputs
outputs = np.array([[1],[0],[1],[0]]) #Expected outputs

We know that we can't change our inputs and our output is dependent on the weights we give it.
#### Random weights = Random outputs 
So, we need a way to optimize our weights such that, it will give us the results we want.
But, First we initialize the weights randomly and then, optimize it over time

In [26]:
np.random.seed(1)
weights = 2 * np.random.random((3, 1))

In [27]:
#Sigmoid function 
def sigmoid(x, deriv=False):
    if(deriv==True):
        return x*(1-x)#derivative
    return 1/(1+np.exp(-x))

In [28]:
for i in range(60000):#here, 60000 is the no. of iterations
    pred = sigmoid(np.dot(inputs, weights))

So, Now we need to optimize weights. The way we're gonna do that is by using gradient descent(one of the trickiest topics to learn). Let's visualize this! Then I'll explain it. Checkout [this](https://spin.atomicobject.com/2014/06/24/gradient-descent-linear-regression/) tutorial. It's great


![](https://qph.ec.quoracdn.net/main-qimg-b7a3a254830ac374818cdce3fa5a7f17)

### Go against the gradient to get to the local minima(Not math) 
    Through calculus, we derive the equations for gradient descents
^^^ image where there's a graph plotted for 1 weight and the error. For, every iteration we calculate the gradient(slope) to get to the local minima(The point where the error is  lowest). And Descenting down the gradient will give us a sene of direction(pos or neg). Then we update the weights by going against the gradient. Check out [this video](https://www.youtube.com/watch?v=jc2IthslyzM) for the math and for the foundation for the gradient descent

In [29]:
for i in range(60000):
	pred = sigmoid(np.dot(inputs, weights))
	error = pred- outputs
	adjustments = np.dot(inputs.T, error* sigmoid(pred, deriv=True))
	weights -= adjustments

In [30]:
#Time to test it
print('Your neural network has finished training!. Let us test this...')
print('Considering New situation ->> [1, 1, 0]')
output_for_test = sigmoid(np.dot(np.array([1,1,0]), weights))
print('predicting..')
print(output_for_test) 

Your neural network has finished training!. Let us test this...
Considering New situation ->> [1, 1, 0]
predicting..
[ 0.99999681]


^ See, 0.9999 was't that bad
##### Congratutlations. You just made a neural network from scratch! :)

In [33]:
#To increase the accuracy you can add more hidden layers, more examples.If you are working on a complex problem
#Example of the same neural network bu with a hidden layer
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
    
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
    
# output dataset            
y = np.array([[0,0,1,1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1

for iter in range(10000):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))

    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)

print ("Output After Training:")
print (l1)


Output After Training:
[[ 0.00966449]
 [ 0.00786506]
 [ 0.99358898]
 [ 0.99211957]]
